### ISSUE TITLE
Maxmind support

### ISSUE THREAD

**Issue by kaihendry** [kikyous/docker-rails#1]
How do I customize your Dockerfile to add Maxmind headers?

e.g. 

```
RUN add-apt-repository ppa:maxmind/ppa && \
apt-get update && \
apt-get install libmaxminddb0 libmaxminddb-dev mmdb-bin -y
```

Appending that to the Dockerfile doesn't work

**Comment by kikyous** [comment]
`apt-get update && apt-get install software-properties-common python-software-properties`

**Comment by kaihendry** [comment]
I don't quite follow?
